/* =========================================================
   File này được TẠO TỰ ĐỘNG bởi admin app (admin/server.py).
   Đừng sửa tay — mở app rồi bấm lưu, file sẽ được ghi lại.
   ========================================================= */

window.PROJECTS = {
  "event-droppii": {
    category: "SOCIAL MEDIA | EVENT",
    title: "GALA ĐẠI HỘI NĂM 2026 DROPPII",
    description: "Trong khuôn khổ Đại hội năm Droppii 2026, Tiến trực tiếp đảm nhiệm việc thực thi toàn bộ giải pháp hình ảnh cho sự kiện, từ các thiết kế Social Post truyền thông trước, trong và sau chương trình, hệ thống POSM in ấn đồng bộ (standee, backdrop, photobooth, thẻ đeo...) cho đến các ấn phẩm in ấn cỡ lớn và hiệu ứng màn hình LED trình chiếu trên sân khấu. Sự tỉ mỉ và đồng bộ trong từng nét vẽ đã góp phần tạo nên một không gian sự kiện chỉn chu, chuyên nghiệp và đầy cảm xúc.",
    images: [
      "assets/project/GALA/thumb dhn.jpg",
      "assets/project/GALA/3.jpg",
      "assets/project/GALA/4.jpg",
      "assets/project/GALA/5.jpg",
      "assets/project/GALA/6.png",
      "assets/project/GALA/7.png",
      "assets/project/GALA/8.png",
      "assets/project/GALA/9.png",
      "assets/project/GALA/10.png",
      "assets/project/GALA/11.png",
      "assets/project/GALA/12.png",
      "assets/project/GALA/13.png",
      "assets/project/GALA/14.jpg",
      "assets/project/GALA/15.jpg",
      "assets/project/GALA/16.png",
      "assets/project/GALA/17.png",
      "assets/project/GALA/18.jpg",
      "assets/project/GALA/19.png",
      "assets/project/GALA/20.jpg",
      "assets/project/GALA/21.jpg",
      "assets/project/GALA/22.jpg",
      "assets/project/GALA/23.jpg",
      "assets/project/GALA/24.jpg",
    ],
  },
  "digital-advertising-droppii": {
    category: "SOCIAL MEDIA | UI - UX DESIGN",
    title: "DIGITAL ADVERTISING DROPPII",
    description: "Các thiết kế Digital Advertising được phát triển nhằm đảm bảo tính đồng nhất thương hiệu, khả năng truyền tải thông tin nhanh và hiệu quả trên các nền tảng số.",
    images: [
      "assets/project/DIGITAL ADVERTISING DROPPII/thumb ads (1).png",
      "assets/project/DIGITAL ADVERTISING DROPPII/153 OPT2.png",
      "assets/project/DIGITAL ADVERTISING DROPPII/180.png",
      "assets/project/DIGITAL ADVERTISING DROPPII/ADS 5.png",
      "assets/project/DIGITAL ADVERTISING DROPPII/2.png",
      "assets/project/DIGITAL ADVERTISING DROPPII/5.png",
      "assets/project/DIGITAL ADVERTISING DROPPII/ADS 4.png",
      "assets/project/DIGITAL ADVERTISING DROPPII/ADS PT TEXT 2.png",
      "assets/project/DIGITAL ADVERTISING DROPPII/181.png",
      "assets/project/DIGITAL ADVERTISING DROPPII/ADS 6.png",
      "assets/project/DIGITAL ADVERTISING DROPPII/LP ADS.png",
      "assets/project/DIGITAL ADVERTISING DROPPII/Landingpage droppii mall sua.png",
      "assets/project/DIGITAL ADVERTISING DROPPII/LP AI (1).png",
    ],
  },
  "expo-hang-moi-droppii": {
    category: "SOCIAL MEDIA | POSM",
    title: "EXPO LÊN KỆ TẾT 2026 DROPPII",
    description: "Expo Lên Kệ Quà Tết 2026 – Droppii là sự kiện giao thương trọng điểm, khởi động chiến dịch kinh doanh mùa lễ hội lớn nhất trong năm của Droppii nhằm kết nối các Nhà phát triển sản phẩm (PDP) với hàng nghìn đối tác kinh doanh. Đồng hành cùng chương trình, Tiến đảm nhiệm toàn bộ khâu thiết kế—từ việc thiết kế các bộ Social Media Post truyền thông sôi nổi trên Fanpage đến việc sản xuất hệ thống POSM in ấn đồng bộ tại sự kiện như standee, backdrop và tờ rơi quảng bá. Sự chỉn chu và không khí Tết rực rỡ trong từng thiết kế đã góp phần tạo nên một không gian triển lãm chuyên nghiệp, thu hút và tối ưu hiệu quả kết nối cho sự kiện.",
    images: [
      "assets/project/EXPO HANG MOI DROPPII/THUMB LEN KE TET.jpg",
      "assets/project/EXPO HANG MOI DROPPII/TEASER LEN KE TET.png",
      "assets/project/EXPO HANG MOI DROPPII/AGENDA HCM.png",
      "assets/project/EXPO HANG MOI DROPPII/bia km (3).png",
      "assets/project/EXPO HANG MOI DROPPII/bia hoat dong.png",
      "assets/project/EXPO HANG MOI DROPPII/BANNER KICK OFF.png",
      "assets/project/EXPO HANG MOI DROPPII/cuoc dua social HCM.png",
      "assets/project/EXPO HANG MOI DROPPII/album qua.jpg",
      "assets/project/EXPO HANG MOI DROPPII/collection qua tet.png",
      "assets/project/EXPO HANG MOI DROPPII/bg expo.jpg",
      "assets/project/EXPO HANG MOI DROPPII/standee expo.jpg",
      "assets/project/EXPO HANG MOI DROPPII/tờ roi.jpg",
      "assets/project/EXPO HANG MOI DROPPII/599951886_2944288952438850_7792830380536633948_n.jpg",
      "assets/project/EXPO HANG MOI DROPPII/600274380_3107105886144380_2849238036044173490_n.jpg",
      "assets/project/EXPO HANG MOI DROPPII/598845054_122363898362001820_8402611299852021771_n.jpg",
    ],
  },
  "expo-health": {
    category: "SOCIAL MEDIA | POSM",
    title: "EXPO SỨC KHỎE DROPPII",
    description: "Meta meta meta",
    images: [
      "assets/project/EXPO SUC KHOE DROPPII/thumb expo (1).png",
      "assets/project/EXPO SUC KHOE DROPPII/DIEM HEN SUC KHOE TEASER 2.png",
      "assets/project/EXPO SUC KHOE DROPPII/bia km.png",
      "assets/project/EXPO SUC KHOE DROPPII/TRAI NGHIEM GI.png",
      "assets/project/EXPO SUC KHOE DROPPII/backdrop.png",
      "assets/project/EXPO SUC KHOE DROPPII/standee.png",
      "assets/project/EXPO SUC KHOE DROPPII/pic.png",
    ],
  },
  "sale-event": {
    category: "SOCIAL MEDIA | UI - UX DESIGN",
    title: "SALE EVENT 28.3 DROPPII",
    description: "Meta meta meta",
    images: [
      "assets/project/SALE EVENT DROPPII/thumb 28.png",
      "assets/project/SALE EVENT DROPPII/teaser.png",
      "assets/project/SALE EVENT DROPPII/full rule 28 vuong.png",
      "assets/project/SALE EVENT DROPPII/full rule 28 vuong 2.png",
      "assets/project/SALE EVENT DROPPII/bia km (1).png",
      "assets/project/SALE EVENT DROPPII/LP.png",
    ],
  },
  "sale-campaign-nhan-duyen": {
    category: "SOCIAL MEDIA | POSM",
    title: "EXPO ĐẠI HỘI NĂM DROPPII 2026",
    description: "EXPO Đại hội năm Droppii 2026 là không gian triển lãm kết nối thương mại quy mô lớn nhất trong năm của Droppii, nơi quy tụ hàng nghìn đối tác kinh doanh cùng các Nhà phát triển sản phẩm (PDP) trên toàn quốc. Trong sự kiện này, Tiến đảm nhiệm toàn bộ quy trình thiết kế thị giác—từ việc sáng tạo chuỗi Social Media Posts truyền thông sôi nổi trên Fanpage đến việc sản xuất đồng bộ hệ thống POSM in ấn tại khu vực triển lãm như standee, backdrop và tờ rơi giới thiệu. Sự chỉn chu, hiện đại và đồng nhất trong từng điểm chạm thiết kế đã góp phần tạo nên một không gian EXPO vô cùng chuyên nghiệp, thu hút và tối ưu hiệu quả kết nối thương hiệu.",
    images: [
      "assets/project/SALE CAMPAIGN NHAN DUYEN/thumb dhn expo.jpg",
      "assets/project/SALE CAMPAIGN NHAN DUYEN/TEASER EXPO 2026.png",
      "assets/project/SALE CAMPAIGN NHAN DUYEN/5 ly do.png",
      "assets/project/SALE CAMPAIGN NHAN DUYEN/7 ngay.png",
      "assets/project/SALE CAMPAIGN NHAN DUYEN/tong hop gian hang.png",
      "assets/project/SALE CAMPAIGN NHAN DUYEN/LAYOUT.png",
      "assets/project/SALE CAMPAIGN NHAN DUYEN/goi y.png",
      "assets/project/SALE CAMPAIGN NHAN DUYEN/BIA KM EXPO.png",
      "assets/project/SALE CAMPAIGN NHAN DUYEN/all logo va sp.png",
      "assets/project/SALE CAMPAIGN NHAN DUYEN/bg dhn expo 1.jpg",
      "assets/project/SALE CAMPAIGN NHAN DUYEN/bg dhn expo 2.jpg",
      "assets/project/SALE CAMPAIGN NHAN DUYEN/bg dhn expo 3.jpg",
      "assets/project/SALE CAMPAIGN NHAN DUYEN/bg dhn expo 4.jpg",
      "assets/project/SALE CAMPAIGN NHAN DUYEN/standee dhn expo 4.jpg",
      "assets/project/SALE CAMPAIGN NHAN DUYEN/phuon.jpg",
      "assets/project/SALE CAMPAIGN NHAN DUYEN/614134822_933545826063425_5592355707203476434_n.jpg",
      "assets/project/SALE CAMPAIGN NHAN DUYEN/611734440_884608580982712_2465037879934288597_n.jpg",
      "assets/project/SALE CAMPAIGN NHAN DUYEN/643272629_33968948406082574_4572946639519520149_n.jpg",
      "assets/project/SALE CAMPAIGN NHAN DUYEN/643831205_33968948089415939_5091610909783105093_n.jpg",
      "assets/project/SALE CAMPAIGN NHAN DUYEN/612265197_884608374316066_5731825006363740329_n.jpg",
      "assets/project/SALE CAMPAIGN NHAN DUYEN/614894603_886839220759648_881431256191728458_n.jpg",
      "assets/project/SALE CAMPAIGN NHAN DUYEN/613304406_932342436183764_4856841816215065587_n.jpg",
      "assets/project/SALE CAMPAIGN NHAN DUYEN/614610462_933545612730113_5774584521769658761_n.jpg",
    ],
  },
  "vu-lan-nhan-duyen": {
    category: "SOCIAL MEDIA | POSM",
    title: "THÁNG PHỤ NỮ DROPPII",
    description: "Trong khuôn khổ chuỗi hoạt động Tháng Phụ Nữ (10/2025) của Droppii—với các chương trình sale ưu đãi cùng không gian EXPO mua sắm ấm cúng, Tiến đảm nhiệm toàn bộ khâu thiết kế thị giác cho chiến dịch. Từ các bộ Social Media Posts bắt mắt trên Fanpage đến hệ thống POSM in ấn gọn gàng tại khu vực trưng bày như standee, backdrop và tờ rơi, từng thiết kế đều được chăm chút chỉn chu, mang tinh thần tôn vinh phái đẹp và tạo điểm nhấn thu hút khách ghé thăm.",
    images: [
      "assets/project/VU LAN NHAN DUYEN/THUMB phu nu.jpg",
      "assets/project/VU LAN NHAN DUYEN/chuc 2010.png",
      "assets/project/VU LAN NHAN DUYEN/bia.png",
      "assets/project/VU LAN NHAN DUYEN/TEASER.png",
      "assets/project/VU LAN NHAN DUYEN/official.png",
      "assets/project/VU LAN NHAN DUYEN/SALE GIUA THANG.png",
      "assets/project/VU LAN NHAN DUYEN/OFFICIAL-SALE-GIUA-THANG.png",
      "assets/project/VU LAN NHAN DUYEN/VOUCHER-FREESHIP-LIVE.png",
      "assets/project/VU LAN NHAN DUYEN/bia km BIZ.png",
      "assets/project/VU LAN NHAN DUYEN/QUA YEU THUONG DOC.png",
      "assets/project/VU LAN NHAN DUYEN/bia km (1).png",
      "assets/project/VU LAN NHAN DUYEN/bg phu nu.jpg",
      "assets/project/VU LAN NHAN DUYEN/standee phu nu.jpg",
      "assets/project/VU LAN NHAN DUYEN/559502623_122227704656105281_4061632812752644012_n.jpg",
    ],
  },
  "king-jades-83": {
    category: "SOCIAL MEDIA",
    title: "3 MÀN LỌC DROPPII - SERIES THE APPROVER",
    description: "Chính sách “3 màng lọc” của Droppii là cam kết chiến lược nhằm nâng cao uy tín hàng hóa, được lan tỏa xuyên suốt qua chuỗi tọa đàm livestream The Approver gồm 4 tập phát sóng trong 4 tháng. Trong chiến dịch dài hơi này, Tiến giữ vai trò định hình thị giác chủ đạo khi sáng tạo toàn bộ Key Visual (KV), bộ bài đăng Social Media truyền thông cho 3 màng lọc và trọn bộ thiết kế phục vụ phát sóng cho Tập 1 khởi động. Sau khi hoàn thiện khung thiết kế chuẩn, Tiến trực tiếp hướng dẫn và dẫn dắt các bạn Intern thực hiện adapt hình ảnh cho 3 tập tiếp theo, đảm bảo tính đồng bộ nhận diện thương hiệu cũng như tối ưu hiệu suất làm việc nhóm.",
    images: [
      "assets/project/KING JADES 8.3/THUMB approver.jpg",
      "assets/project/KING JADES 8.3/3 LOP.png",
      "assets/project/KING JADES 8.3/vuong 3 lop 1.png",
      "assets/project/KING JADES 8.3/vuong 3 lop 2.png",
      "assets/project/KING JADES 8.3/vuong 3 lop 3.png",
      "assets/project/KING JADES 8.3/3 MANG LOC.png",
      "assets/project/KING JADES 8.3/APPROVER teaser (1).png",
      "assets/project/KING JADES 8.3/official (1).png",
      "assets/project/KING JADES 8.3/QUOTE minh chau.png",
      "assets/project/KING JADES 8.3/QUOTE thu ha.png",
      "assets/project/KING JADES 8.3/QUOTE mai hau 2.png",
      "assets/project/KING JADES 8.3/QUOTE KIM PHUNG.png",
      "assets/project/KING JADES 8.3/cau 1.png",
      "assets/project/KING JADES 8.3/cau 2.png",
      "assets/project/KING JADES 8.3/cau 3.png",
      "assets/project/KING JADES 8.3/thumb.jpg",
      "assets/project/KING JADES 8.3/thumb (1).jpg",
      "assets/project/KING JADES 8.3/mang loc 4.png",
      "assets/project/KING JADES 8.3/mang loc 4 2.png",
      "assets/project/KING JADES 8.3/mang loc 4 3.png",
      "assets/project/KING JADES 8.3/mang loc 4 4.png",
      "assets/project/KING JADES 8.3/mang loc 4 5.png",
    ],
  },
  "fnb-menu": {
    category: "SOCIAL MEDIA",
    title: "SALE EVENT 1.6 DROPPII",
    description: "Sale Event 1.6 Droppii – Phá Đảo Thế Giới Deal là chiến dịch mua sắm bùng nổ nhân dịp Lễ Thiếu nhi, mang đến chuỗi ưu đãi lớn cho khách hàng và đối tác. Đồng hành cùng chiến dịch, Tiến trực tiếp đảm nhiệm toàn bộ khâu thiết kế Social Media Posts trên Fanpage, sáng tạo Key Visual lấy ý tưởng từ thế giới Game Mario kinh điển. Bằng cách lồng ghép khéo léo các yếu tố đồ họa Pixel/3D vui nhộn, năng động cùng bố cục hình ảnh bắt mắt, bộ thiết kế đã truyền tải trọn vẹn tinh thần \"phá đảo\" đầy hứng khởi, thu hút tương tác mạnh mẽ và tạo điểm nhấn độc đáo cho chiến dịch.",
    images: [
      "assets/project/FNB MENU/THUMB 16.jpg",
      "assets/project/FNB MENU/PHA DAO THE GIOI DEAL.png",
      "assets/project/FNB MENU/teaser 2.png",
      "assets/project/FNB MENU/BANNER LIVE biz.png",
      "assets/project/FNB MENU/bia km (4).png",
      "assets/project/FNB MENU/goi y qua 16.png",
      "assets/project/FNB MENU/chuc 1_6.png",
    ],
  },
  "project-moi-1": {
    category: "SOCIAL MEDIA | EVENT",
    title: "GALA ĐẠI HỘI NĂM DROPPII 2024 - 2025",
    description: "Gala Đại hội năm Droppii (với các chủ đề “Vượt Sóng Ra Khơi” năm 2024 và “Theo Ánh Mặt Trời” năm 2025) là đêm hội tôn vinh và bùng nổ cảm xúc quan trọng nhất trong năm của thương hiệu. Đồng hành cùng hai mùa Gala, Tiến đảm nhiệm khâu triển khai hình ảnh truyền thông trên Fanpage—từ việc phát triển các bộ Social Media Posts dựa trên Key Visual (KV) sẵn có cho đến việc xử lý tỉ mỉ hình ảnh các nghệ sĩ khách mời. Sự khéo léo trong bố cục và chuẩn xác về nhận diện đã giúp truyền tải trọn vẹn tinh thần chủ đạo của đêm tiệc, tạo sức hút truyền thông mạnh mẽ cho sự kiện.",
    images: [
      "assets/project/PROJECT MOI 1/thumb dhn 2.jpg",
      "assets/project/PROJECT MOI 1/agenda gala.png",
      "assets/project/PROJECT MOI 1/thumbnail recap dhn.png",
      "assets/project/PROJECT MOI 1/remind gala 23.png",
      "assets/project/PROJECT MOI 1/Hướng dẫn line check in (Gala).png",
      "assets/project/PROJECT MOI 1/hang muc.png",
      "assets/project/PROJECT MOI 1/vuong rewind 222.png",
      "assets/project/PROJECT MOI 1/banner app DHN.png",
      "assets/project/PROJECT MOI 1/banner live TAMT.png",
      "assets/project/PROJECT MOI 1/nhin lai 2024.png",
      "assets/project/PROJECT MOI 1/MINIGAME DHN.png",
      "assets/project/PROJECT MOI 1/alb quote.png",
    ],
  },
  "1": {
    category: "SOCIAL MEDIA",
    title: "SERIES KHOẢNH KHẮC VÔ GIÁ DROPPII",
    description: "Series bài viết “Khoảnh Khắc Vô Giá” trên Fanpage Droppii là không gian lắng đọng để ghi dấu và tôn vinh hành trình nỗ lực của các đối tác kinh doanh thông qua những chuyến du lịch tưởng thưởng hàng năm. Đồng hành cùng chiến dịch, Tiến trực tiếp thiết kế toàn bộ các bài đăng Social Media, tập trung vào việc trau chuốt hình ảnh, khéo léo lồng ghép cảm xúc và duy trì tính đồng bộ với nhận diện thương hiệu. Từng thiết kế không chỉ tái hiện trọn vẹn những khoảnh khắc đáng nhớ mà còn tạo cảm hứng truyền động lực mạnh mẽ tới cộng đồng đối tác Droppii.",
    images: [
      "assets/project/1/THUMB kkvg.jpg",
      "assets/project/1/khoanh khac 2.png",
      "assets/project/1/post 1.png",
      "assets/project/1/post 2.png",
      "assets/project/1/post 3png.png",
      "assets/project/1/post 4.png",
    ],
  },
  "yen-sao": {
    category: "KEY VISUAL | TRAVEL",
    title: "KV DROPPII TRAVEL - COMPANY TRIP",
    description: "Chương trình Droppii Travel (du lịch tưởng thưởng dành cho đối tác) và Company Trip (du lịch nội bộ) là những hoạt động thường niên trọng điểm, nhằm tôn vinh những cống hiến vượt bậc và gắn kết tinh thần tập thể. Trong các chiến dịch này, Tiến đóng vai trò cốt lõi khi sáng tạo và phát triển các bộ Key Visual (KV) chủ đạo—định hình phong cách thị giác và thông điệp cho toàn bộ chuyến đi. Tệp thiết kế này sau đó được chuyển giao để các đơn vị agency du lịch adapt thành hệ thống ấn phẩm in ấn thực tế (backdrop, standee, banner, quà tặng...), đảm bảo tính đồng bộ, chỉn chu và trải nghiệm trọn vẹn cho người tham gia.",
    images: [
      "assets/project/YEN SAO/THUMB travel.jpg",
      "assets/project/YEN SAO/kv bali.png",
      "assets/project/YEN SAO/KV CHAMPION.png",
      "assets/project/YEN SAO/KV NHA TRANG 2.png",
    ],
  },
  "vitaleaf": {
    category: "SOCIAL MEDIA",
    title: "LÁ GAN NGUỒN SỐNG - VITALEAF X DROPPII",
    description: "Chương trình “Lá Gan Nguồn Sống” (07/2025) là dự án hợp tác chiến lược giữa Droppii và Vitaleaf—với vai trò Vitaleaf là Nhà tài trợ đồng hành cùng chiến dịch 90 Ngày Tốc Chiến 2025 nhằm nâng cao nhận thức chăm sóc sức khỏe chủ động cho cộng đồng. Trong dự án này, Tiến đảm nhiệm toàn bộ khâu sáng tạo và triển khai thiết kế Social Media Posts trên Fanpage. Bằng tư duy thị giác hiện đại, sự kết hợp hài hòa giữa nhận diện thương hiệu Vitaleaf và tinh thần năng động của Droppii, các thiết kế không chỉ truyền tải trọn vẹn thông điệp sức khỏe giá trị mà còn góp phần gia tăng tương tác, thu hút sự chú ý mạnh mẽ trong mùa tốc chiến.",
    images: [
      "assets/project/VITALEAF/thumb lgns.jpg",
      "assets/project/VITALEAF/la gan.png",
      "assets/project/VITALEAF/post gan.jpg",
      "assets/project/VITALEAF/hv 6.png",
      "assets/project/VITALEAF/banner matching m3.png",
      "assets/project/VITALEAF/NGAY HOI VITA LEAF APP.png",
      "assets/project/VITALEAF/BANNER XU HUONG VITA LEAF SUA.png",
      "assets/project/VITALEAF/BANNER XU HUONG VITA LEAF 2.png",
      "assets/project/VITALEAF/CHAO SAN VITA LEAF 2.png",
      "assets/project/VITALEAF/MIEN KY QUY T7.png",
      "assets/project/VITALEAF/lo trinh.jpg",
      "assets/project/VITALEAF/MINIGAME VITA.png",
      "assets/project/VITALEAF/FREESHIP VITA LEAF 169.png",
    ],
  },
  "3": {
    category: "SOCIAL MEDIA",
    title: "BẬT ĐÀ TIỀM NĂNG - DROPPII X MIDU",
    description: "Chương trình “Bật Đà Tiềm Năng” (02/2026)—dự án hợp tác chiến lược giữa Droppii và thương hiệu Midu—được triển khai nhằm khai phá cơ hội bứt phá kinh doanh cho cộng đồng đối tác. Trong chiến dịch này, Tiến trực tiếp đảm nhiệm toàn bộ khâu sáng tạo và triển khai thiết kế Social Media Posts trên Fanpage. Bằng việc kết hợp tinh tế giữa nhận diện riêng của hai thương hiệu, bố cục hình ảnh hiện đại cùng tinh thần truyền cảm hứng mạnh mẽ, các thiết kế đã tạo nên điểm chạm thị giác chuyên nghiệp, thu hút sự chú ý lớn và lan tỏa hiệu quả thông điệp của chương trình.",
    images: [
      "assets/project/3/thumb midu.jpg",
      "assets/project/3/teaser (1).png",
      "assets/project/3/post midu.png",
      "assets/project/3/Banner live (2).png",
      "assets/project/3/Giải thưởng.png",
      "assets/project/3/ebook.png",
      "assets/project/3/REMIND (2).png",
      "assets/project/3/X2 MUNG 1.png",
      "assets/project/3/x2 mung 10.png",
    ],
  },
  "2": {
    category: "SOCIAL MEDIA | UI - UX DESIGN",
    title: "TẾT ĐẾN GẦN DROPPII",
    description: "Sale Event “Tết Đến Gần” (30.01.2026) của Droppii là chiến dịch kích cầu mua sắm trọng điểm giai đoạn cận Tết, mang không khí rộn ràng cùng chuỗi ưu đãi lớn đến cho khách hàng và đối tác. Đồng hành cùng chiến dịch, Tiến trực tiếp đảm nhiệm toàn bộ khâu sáng tạo thị giác—từ việc thiết kế trọn bộ Social Media Posts sôi nổi trên Fanpage đến việc xây dựng giao diện Landing Page tối ưu trải nghiệm người dùng. Sự kết hợp hài hòa giữa màu sắc Tết truyền thống và nét thiết kế hiện đại đã tạo nên điểm chạm thị giác ấn tượng, góp phần thúc đẩy tỷ lệ chuyển đổi và lan tỏa sức nóng cho sự kiện.",
    images: [
      "assets/project/2/thumb tet den gan.jpg",
      "assets/project/2/BIA KM (5).png",
      "assets/project/2/POSTER (1).png",
      "assets/project/2/BANNER LIVE (3).png",
      "assets/project/2/FREESHIP.png",
      "assets/project/2/NHAN LICH (1).png",
      "assets/project/2/LP (1).png",
    ],
  },
  "ooh": {
    category: "SOCIAL MEDIA | PRINTING",
    title: "CHAY NHÂN DUYÊN - TỆP KHÁCH HOA",
    description: "Nhà hàng chay Nhân Duyên là điểm đến ẩm thực thanh tịnh, gói trọn hương vị thực dưỡng lành mạnh và rất được lòng cộng đồng người Hoa tại TP.HCM. Đồng hành cùng định hướng truyền thông của nhà hàng, Tiến trực tiếp đảm nhiệm khâu sáng tạo thị giác—từ việc thiết kế các bộ Social Media Posts bắt mắt, chuẩn phong cách văn hóa trên Fanpage cho đến việc adapt linh hoạt sang hệ thống ấn phẩm in ấn thực tế như băng rôn, standee và poster A5 để bàn. Sự tinh tế trong từng đường nét thiết kế không chỉ tôn vinh nét đẹp ẩm thực chay mà còn tạo sự kết nối gần gũi, thu hút hiệu quả tệp thực khách người Hoa tại địa phương.",
    images: [
      "assets/project/OOH - PANO - BACKDROP/thumb nhan duyen hoa.jpg",
      "assets/project/OOH - PANO - BACKDROP/typo (1).png",
      "assets/project/OOH - PANO - BACKDROP/SOCIAL DAT BAN NHAN MON .png",
      "assets/project/OOH - PANO - BACKDROP/HANH TRINH TAM BAO VUONG.png",
      "assets/project/OOH - PANO - BACKDROP/RULE HANH TRINH TAM BAO.png",
      "assets/project/OOH - PANO - BACKDROP/kim co chi bao.png",
      "assets/project/OOH - PANO - BACKDROP/mon goi 2.png",
      "assets/project/OOH - PANO - BACKDROP/DIMSUM VA TRA.png",
      "assets/project/OOH - PANO - BACKDROP/nam nhay tuong.png",
      "assets/project/OOH - PANO - BACKDROP/post ds.png",
      "assets/project/OOH - PANO - BACKDROP/1 binh tan.png",
      "assets/project/OOH - PANO - BACKDROP/2 (2).png",
      "assets/project/OOH - PANO - BACKDROP/adss.png",
      "assets/project/OOH - PANO - BACKDROP/Set MỘC LIÊN (1).png",
      "assets/project/OOH - PANO - BACKDROP/Set NGỌC HỶ (1).png",
      "assets/project/OOH - PANO - BACKDROP/Set TUỆ TÂM fix (1).png",
      "assets/project/OOH - PANO - BACKDROP/kim ngoc man duong social.png",
      "assets/project/OOH - PANO - BACKDROP/album mon moi.png",
      "assets/project/OOH - PANO - BACKDROP/an chay tich phuoc.png",
      "assets/project/OOH - PANO - BACKDROP/via quan cong.png",
    ],
  },
  "logofolio": {
    category: "SOCIAL MEDIA | PRINTING",
    title: "CHAY NHÂN DUYÊN - TỆP KHÁCH VIỆT",
    description: "Nhà hàng chay Nhân Duyên là điểm đến quen thuộc dành cho những ai tìm kiếm không gian ẩm thực thanh tịnh cùng các món chay thực dưỡng, trọn vị và lành lành. Đồng hành cùng hình ảnh của nhà hàng, Tiến đảm nhiệm toàn bộ khâu sáng tạo thị giác—từ việc thiết kế các bộ Social Media Posts chỉn chu, thu hút trên Fanpage đến việc adapt linh hoạt sang hệ thống ấn phẩm in ấn thực tế như băng rôn, standee truyền thông và poster A5 để bàn. Sự đồng bộ từ không gian mạng đến điểm chạm tại nhà hàng đã góp phần mang hình ảnh Nhân Duyên đến gần hơn với thực khách, nhẹ nhàng nhưng đầy ấn tượng.",
    images: [
      "assets/project/LOGOFOLIO/thumb nhan duyen.jpg",
      "assets/project/LOGOFOLIO/gio vang.jpg",
      "assets/project/LOGOFOLIO/dbnm.jpg",
      "assets/project/LOGOFOLIO/social khai truong.png",
      "assets/project/LOGOFOLIO/social retouch.png",
      "assets/project/LOGOFOLIO/social mung 1.png",
      "assets/project/LOGOFOLIO/trang mieng.png",
      "assets/project/LOGOFOLIO/tri an.png",
      "assets/project/LOGOFOLIO/set phung duong.png",
      "assets/project/LOGOFOLIO/MENU TU CHON vuong.png",
      "assets/project/LOGOFOLIO/com chien trai thom.png",
      "assets/project/LOGOFOLIO/pho chay.png",
      "assets/project/LOGOFOLIO/cover.png",
      "assets/project/LOGOFOLIO/cover page vu lan.png",
      "assets/project/LOGOFOLIO/loi nhac.png",
      "assets/project/LOGOFOLIO/com viet.jpg",
      "assets/project/LOGOFOLIO/vu lan.png",
      "assets/project/LOGOFOLIO/1 thang 5 1.png",
      "assets/project/LOGOFOLIO/moc khoa dimsum 2.png",
      "assets/project/LOGOFOLIO/2.9.png",
      "assets/project/LOGOFOLIO/tang 20.10.png",
      "assets/project/LOGOFOLIO/SOCIAL SET SEN.png",
      "assets/project/LOGOFOLIO/SOCIAL VU LAN.png",
      "assets/project/LOGOFOLIO/trung thu poster.png",
      "assets/project/LOGOFOLIO/chuc mung 8.3.png",
      "assets/project/LOGOFOLIO/huong yeu 8.3.png",
      "assets/project/LOGOFOLIO/thich quang duc (1).png",
      "assets/project/LOGOFOLIO/thu ngo.png",
      "assets/project/LOGOFOLIO/tang nen thom social.png",
    ],
  },
  "project-moi-2": {
    category: "SOCIAL MEDIA | POSM",
    title: "VÒNG NGỌC KING JADES",
    description: "King Jades là thương hiệu vòng ngọc phong thủy cao cấp, nổi tiếng với những thiết kế trang sức ngọc thiên nhiên tinh xảo, mang lại may mắn và vẻ đẹp sang trọng cho người đeo. Đồng hành cùng định hướng hình ảnh của thương hiệu, Tiến trực tiếp đảm nhiệm khâu sáng tạo thị giác—từ việc thiết kế các bộ Social Posts chỉn chu, quý phái trên Fanpage đến việc sản xuất đồng bộ hệ thống POSM thực tế như standee và poster A5 để bàn. Sự tỉ mỉ trong từng đường nét và màu sắc thiết kế đã góp phần tôn vinh giá trị đẳng cấp của sản phẩm, đồng thời tạo điểm chạm thị giác ấn tượng với khách hàng.",
    images: [
      "assets/project/PROJECT MOI 2/thumb KINGJADE.png",
      "assets/project/PROJECT MOI 2/banner zalo black friday.png",
      "assets/project/PROJECT MOI 2/banner zalo kich hoat tai loc.png",
      "assets/project/PROJECT MOI 2/Siêu sale cuối năm.png",
      "assets/project/PROJECT MOI 2/chuc mung nam moi opt 3.jpg",
      "assets/project/PROJECT MOI 2/cover page.png",
      "assets/project/PROJECT MOI 2/UU DAI TET.png",
      "assets/project/PROJECT MOI 2/ava page.png",
    ],
  },
  "project-moi-4": {
    category: "LARGE SCLAE PRINTING",
    title: "OOH - PANO",
    description: "Với lợi thế tư duy thị giác cỡ lớn và khả năng xử lý bố cục chuẩn xác, Tiến đã từng trực tiếp triển khai nhiều dự án OOH & Pano ngoài trời cho các đối tác lớn như Droppii và Bệnh viện Đa khoa Tâm Anh. Từ những biển Pano tấm lớn đặt tại các vị trí đắc địa đến hệ thống bảng biển ngoài trời, các thiết kế luôn đảm bảo sự tối giản, cô đọng thông điệp, tối ưu khả năng nhận diện thương hiệu ngay từ cái nhìn đầu tiên và đáp ứng hoàn hảo các tiêu chuẩn in ấn kỹ thuật cao.",
    images: [
      "assets/project/PROJECT MOI 4/thumb ooh.png",
      "assets/project/PROJECT MOI 4/ooh.png",
      "assets/project/PROJECT MOI 4/482060000_637016059075300_7423239404543374676_n.jpg",
      "assets/project/PROJECT MOI 4/481205044_637016065741966_2972354016353524401_n.jpg",
      "assets/project/PROJECT MOI 4/481957965_640000128776893_2093790120869678526_n.jpg",
      "assets/project/PROJECT MOI 4/481243410_640000285443544_7297242368093751569_n.jpg",
      "assets/project/PROJECT MOI 4/481236545_640000242110215_8297018304055706494_n.jpg",
      "assets/project/PROJECT MOI 4/482004536_640000342110205_8902323921238406522_n.jpg",
      "assets/project/PROJECT MOI 4/1788408486773_2299389257586383672_1378275671276150513_7936865ee806524fcf56f85af678b9ad.jpg",
      "assets/project/PROJECT MOI 4/thumb pano.png",
    ],
  },
  "project-moi-3": {
    category: "PRINTING",
    title: "FNB MENU DESIGN",
    description: "",
    images: [
      "assets/project/PROJECT MOI 3/Group 4 copy.png",
    ],
  },
  "bingto-vlog": {
    category: "KEY VISUAL  |  SOCIAL MEDIA",
    title: "BINGTO VLOG - ĐIỀN QUÂN NETWORK",
    description: "BingTo Vlog là series phim ngắn 5 tập siêu dễ thương của Điền Quân Network và đạo diễn Đỗ Nam, xoay quanh những câu chuyện dở khóc dở cười giữa bộ đôi thú cưng: bé khỉ BingBoong (“Cô 8”) lanh lợi và chú cún ToTo (“Chú 9”) ngây thơ. Trong dự án này, Tiến trực tiếp thiết kế Key Visual (KV) chủ đạo cho bộ phim. Với sắc màu tươi sáng và tạo hình nhân vật ngộ nghĩnh, thiết kế KV đã bắt trọn tinh thần lầy lội, đáng yêu của hai bạn nhỏ, tạo ấn tượng thị giác mạnh mẽ để thu hút khán giả theo dõi series trên YouTube DIEN QUAN Film.",
    images: [
      "assets/project/ĐIỀN QUÂN NETWORK/thumb bing to.png",
      "assets/project/ĐIỀN QUÂN NETWORK/bingto vlog poster.png",
    ],
  },
  "project-moi-5": {
    category: "SOCIAL MEDIA",
    title: "NƯỚC ION KỀM FUJIWA",
    description: "Fujiwa là thương hiệu nước uống ion kiềm cao cấp hàng đầu, nổi tiếng với các sản phẩm chăm sóc sức khỏe chất lượng cao ứng dụng công nghệ hiện đại Nhật Bản. Đồng hành cùng sự phát triển hình ảnh của thương hiệu, Tiến trực tiếp đảm nhiệm khâu sáng tạo và sản xuất các bộ Social Posts đăng tải hàng ngày trên Fanpage. Bằng phong cách thiết kế hiện đại, chỉn chu cùng khả năng tối ưu hóa nhận diện thương hiệu, các sản phẩm thị giác không chỉ truyền tải rõ ràng thông điệp sống khỏe mà còn duy trì sự gắn kết và tương tác đều đặn với cộng đồng người tiêu dùng.",
    images: [
      "assets/project/PROJECT MOI 5/thumb fujiwa (1).png",
      "assets/project/PROJECT MOI 5/1eebbd176320869.64c28ed17b0f1.png",
      "assets/project/PROJECT MOI 5/859554176320869.64c28ed17ffaa.png",
      "assets/project/PROJECT MOI 5/f8a144176320869.64c28ed180e9c.png",
      "assets/project/PROJECT MOI 5/d4af70176320869.64c28ed181b90.png",
      "assets/project/PROJECT MOI 5/0d31d3176320869.64c28ed17ee8f.png",
      "assets/project/PROJECT MOI 5/ff5e25176320869.64e61eb186f8d.png",
      "assets/project/PROJECT MOI 5/f4defd176320869.64e61eb187e29.png",
      "assets/project/PROJECT MOI 5/7dddda176320869.64c28ed17a35c.png",
      "assets/project/PROJECT MOI 5/085660176320869.64e61eb188b7a.png",
      "assets/project/PROJECT MOI 5/cc0400176320869.64c28ed17bed8.png",
      "assets/project/PROJECT MOI 5/581816176320869.64e61eb189940.png",
      "assets/project/PROJECT MOI 5/5-hoat-dong-ngay-he-4.png",
      "assets/project/PROJECT MOI 5/5-hoat-dong-ngay-he-5.png",
      "assets/project/PROJECT MOI 5/5-hoat-dong-ngay-he-6.png",
    ],
  },
  "project-moi-6": {
    category: "SOCIAL MEDIA",
    title: "DUNG DỊCH VỆ SINH LADU LENCO",
    description: "Ladu Lenco là thương hiệu chăm sóc cá nhân nam giới hiện đại, ra mắt thị trường với dòng sản phẩm dung dịch vệ sinh nam cao cấp nhằm mang đến giải pháp tự tin và toàn diện cho phái mạnh. Trong chiến dịch ra mắt sản phẩm, Tiến trực tiếp đảm nhiệm khâu thiết kế chuỗi Social Posts giới thiệu trên nền tảng số. Bằng tư duy thị giác nam tính, tối giản nhưng vô cùng cuốn hút, các thiết kế không chỉ làm nổi bật đặc tính và phong cách của sản phẩm mà còn tạo ấn tượng thị giác mạnh mẽ, góp phần thu hút sự chú ý của khách hàng ngay trong giai đoạn chào sân.",
    images: [
      "assets/project/PROJECT MOI 6/bot ve sinh nam.png",
      "assets/project/PROJECT MOI 6/ddvs nam 1.png",
      "assets/project/PROJECT MOI 6/ddvs nam 2.png",
      "assets/project/PROJECT MOI 6/ddvs nam 3.png",
      "assets/project/PROJECT MOI 6/ddvs nam 4.png",
      "assets/project/PROJECT MOI 6/ddvs nam 5.png",
    ],
  },
  "project-moi-7": {
    category: "LOGO | SOCIAL MEDIA | PRINTING",
    title: "GOODDY BAR - ĐỨC",
    description: "GOODDY Restaurant & Bar là một góc ẩm thực và giải trí ấm cúng tại Hamburg, Đức, nổi bật với không gian nhỏ xinh, mang tinh thần phóng khoáng nhưng vẫn rất gần gũi. Đồng hành cùng dự án từ những ngày đầu, Tiến trực tiếp sáng tạo Logo nhận diện và Poster khai trương cho quán. Thiết kế tập trung vào sự tinh tế, cô đọng, vừa lột tả trọn vẹn cái \"vibe\" ấm áp, chill chill của một không gian bar thu nhỏ, vừa tạo điểm nhấn ấn tượng để thu hút thực khách ngay từ ngày đầu mở cửa.",
    images: [
      "assets/project/PROJECT MOI 7/thumb bar.png",
      "assets/project/PROJECT MOI 7/GOODY LOGO PNG.png",
      "assets/project/PROJECT MOI 7/poster bar.png",
      "assets/project/PROJECT MOI 7/528327068_122119895948932701_6307129062458487922_n.jpg",
      "assets/project/PROJECT MOI 7/519095977_122114488316932701_2564112330347380035_n.jpg",
      "assets/project/PROJECT MOI 7/518196310_122107122302932701_1557275460819053808_n.jpg",
    ],
  },
  "project-moi-8": {
    category: "EVENT  | PRESENTATION",
    title: "CHƯƠNG TRÌNH ĐÀO TẠO CEO - VCCI",
    description: "Chương trình Đào tạo CEO 2023 do VCCI (Liên đoàn Thương mại và Công nghiệp Việt Nam) tổ chức là khóa huấn luyện cao cấp nhằm nâng tầm năng lực quản trị cho các nhà lãnh đạo doanh nghiệp. Đồng hành cùng sự kiện quy mô này, Tiến trực tiếp thực hiện trọn bộ thiết kế thị giác—từ standee điện tử, backdrop điện tử, ấn phẩm OOH ngoài trời cho đến hệ thống màn hình thuyết trình sân khấu. Sự đồng bộ, sang trọng và chỉn chu trong từng chi tiết thiết kế đã góp phần tôn vinh tính chuyên nghiệp và vị thế cấp cao của chương trình.",
    images: [
      "assets/project/PROJECT MOI 8/thumb vcci (1).jpg",
      "assets/project/PROJECT MOI 8/ooh.jpg",
      "assets/project/PROJECT MOI 8/bg 2.jpg",
      "assets/project/PROJECT MOI 8/bg 1.jpg",
      "assets/project/PROJECT MOI 8/STANDEE VCCI.jpg",
      "assets/project/PROJECT MOI 8/bg mockup.png",
      "assets/project/PROJECT MOI 8/D2200345.JPG",
      "assets/project/PROJECT MOI 8/82f1bb178328701.64e6145af0b3f.jpg",
      "assets/project/PROJECT MOI 8/65edd0178328701.64e6145af1aa2.png",
    ],
  },
  "project-moi-9": {
    category: "Course assignment",
    title: "ART DIRECTION - DẤU ẤN DI SẢN BITIS",
    description: "Đồ án “Art Direction – Dấu Ấn Di Sản Biti’s” là dự án sáng tạo thuộc khóa học Art Direction tại trung tâm BOLD, được thực hiện bởi nhóm 2 thành viên nhằm xây dựng định hướng nghệ thuật cho một dòng sản phẩm giày giả tưởng mang đậm chất liệu văn hóa Hát Bội của Biti's. Trong dự án này, Tiến trực tiếp đảm nhiệm toàn bộ khâu nghiên cứu, xây dựng Moodboard và phát triển Key Visual (KV) chủ đạo. Bằng cách chắt lọc tinh hoa từ màu sắc, đường nét mặt nạ tuồng cổ và kết hợp hài hòa với ngôn ngữ thiết kế hiện đại, các sản phẩm thị giác không chỉ tôn vinh giá trị di sản dân tộc mà còn mang lại diện mạo năng động, mới mẻ cho dòng sản phẩm.",
    images: [
      "assets/project/PROJECT MOI 9/dau an di san (1).png",
      "assets/project/PROJECT MOI 9/dau an di san slide 1 (1).png",
      "assets/project/PROJECT MOI 9/sdm2.png",
      "assets/project/PROJECT MOI 9/moodboard (1).png",
      "assets/project/PROJECT MOI 9/art style.png",
      "assets/project/PROJECT MOI 9/chat lieu.png",
      "assets/project/PROJECT MOI 9/IMGST1.png",
      "assets/project/PROJECT MOI 9/color (1).png",
      "assets/project/PROJECT MOI 9/talent.png",
      "assets/project/PROJECT MOI 9/typo (2).png",
      "assets/project/PROJECT MOI 9/kv (1).png",
      "assets/project/PROJECT MOI 9/kv dads.png",
    ],
  },
  "project-moi-10": {
    category: "BRANDING",
    title: "LOGOFOLIO - NHIỀU THƯƠNG HIỆU",
    description: "",
    images: [
      "assets/project/PROJECT MOI 10/1784980741146_2299389257586383672_7062042480160280272_69c2a9cf05e87346a59c273c590cfc59.jpg",
    ],
  },
};
