/* =========================================================
   File này được TẠO TỰ ĐỘNG bởi admin app (admin/server.py).
   Đừng sửa tay — mở app rồi bấm lưu, file sẽ được ghi lại.
   ========================================================= */

window.PROJECTS = {
  "event-droppii": {
    category: "SOCIAL MEDIA | EVENT",
    title: "GALA ĐẠI HỘI NĂM 2026 DROPPII",
    description: "Trong khuôn khổ Đại hội năm Droppii 2026, Tiến trực tiếp đảm nhiệm việc thực thi toàn bộ giải pháp hình ảnh cho sự kiện, từ các thiết kế Social Post truyền thông trước, trong và sau chương trình, hệ thống POSM in ấn đồng bộ (standee, backdrop, photobooth, thẻ đeo...) cho đến các ấn phẩm in ấn cỡ lớn và hiệu ứng màn hình LED trình chiếu trên sân khấu. Sự tỉ mỉ và đồng bộ trong từng nét vẽ đã góp phần tạo nên một không gian sự kiện chỉn chu, chuyên nghiệp và đầy cảm xúc.",
    images: [
      "assets/project/GALA/thumb dhn.jpg",
      "assets/project/GALA/video.mp4",
      "assets/project/GALA/3.jpg",
      "assets/project/GALA/4.jpg",
      "assets/project/GALA/5.jpg",
      "assets/project/GALA/6.png",
      "assets/project/GALA/7.png",
      "assets/project/GALA/8.png",
      "assets/project/GALA/9.png",
      "assets/project/GALA/10.png",
      "assets/project/GALA/11.png",
      "assets/project/GALA/12.png",
      "assets/project/GALA/13.png",
      "assets/project/GALA/14.jpg",
      "assets/project/GALA/15.jpg",
      "assets/project/GALA/16.png",
      "assets/project/GALA/17.png",
      "assets/project/GALA/18.jpg",
      "assets/project/GALA/19.png",
      "assets/project/GALA/20.jpg",
      "assets/project/GALA/21.jpg",
      "assets/project/GALA/22.jpg",
      "assets/project/GALA/23.jpg",
      "assets/project/GALA/24.jpg",
    ],
  },
  "digital-advertising-droppii": {
    category: "SOCIAL MEDIA | UI - UX DESIGN",
    title: "DIGITAL ADVERTISING DROPPII",
    description: "Các thiết kế Digital Advertising được phát triển nhằm đảm bảo tính đồng nhất thương hiệu, khả năng truyền tải thông tin nhanh và hiệu quả trên các nền tảng số.",
    images: [
      "assets/project/DIGITAL ADVERTISING DROPPII/thumb ads (1).png",
      "assets/project/DIGITAL ADVERTISING DROPPII/153 OPT2.png",
      "assets/project/DIGITAL ADVERTISING DROPPII/180.png",
      "assets/project/DIGITAL ADVERTISING DROPPII/ADS 5.png",
      "assets/project/DIGITAL ADVERTISING DROPPII/2.png",
      "assets/project/DIGITAL ADVERTISING DROPPII/5.png",
      "assets/project/DIGITAL ADVERTISING DROPPII/ADS 4.png",
      "assets/project/DIGITAL ADVERTISING DROPPII/ADS PT TEXT 2.png",
      "assets/project/DIGITAL ADVERTISING DROPPII/181.png",
      "assets/project/DIGITAL ADVERTISING DROPPII/ADS 6.png",
      "assets/project/DIGITAL ADVERTISING DROPPII/LP ADS.png",
      "assets/project/DIGITAL ADVERTISING DROPPII/Landingpage droppii mall sua.png",
      "assets/project/DIGITAL ADVERTISING DROPPII/LP AI (1).png",
    ],
  },
  "expo-hang-moi-droppii": {
    category: "SOCIAL MEDIA | POSM",
    title: "EXPO LÊN KỆ TẾT 2026 DROPPII",
    description: "Expo Lên Kệ Quà Tết 2026 – Droppii là sự kiện giao thương trọng điểm, khởi động chiến dịch kinh doanh mùa lễ hội lớn nhất trong năm của Droppii nhằm kết nối các Nhà phát triển sản phẩm (PDP) với hàng nghìn đối tác kinh doanh. Đồng hành cùng chương trình, Tiến đảm nhiệm toàn bộ khâu thiết kế—từ việc thiết kế các bộ Social Media Post truyền thông sôi nổi trên Fanpage đến việc sản xuất hệ thống POSM in ấn đồng bộ tại sự kiện như standee, backdrop và tờ rơi quảng bá. Sự chỉn chu và không khí Tết rực rỡ trong từng thiết kế đã góp phần tạo nên một không gian triển lãm chuyên nghiệp, thu hút và tối ưu hiệu quả kết nối cho sự kiện.",
    images: [
      "assets/project/EXPO HANG MOI DROPPII/THUMB LEN KE TET.jpg",
      "assets/project/EXPO HANG MOI DROPPII/TEASER LEN KE TET.png",
      "assets/project/EXPO HANG MOI DROPPII/AGENDA HCM.png",
      "assets/project/EXPO HANG MOI DROPPII/bia km (3).png",
      "assets/project/EXPO HANG MOI DROPPII/bia hoat dong.png",
      "assets/project/EXPO HANG MOI DROPPII/BANNER KICK OFF.png",
      "assets/project/EXPO HANG MOI DROPPII/cuoc dua social HCM.png",
      "assets/project/EXPO HANG MOI DROPPII/album qua.jpg",
      "assets/project/EXPO HANG MOI DROPPII/collection qua tet.png",
      "assets/project/EXPO HANG MOI DROPPII/bg expo.jpg",
      "assets/project/EXPO HANG MOI DROPPII/standee expo.jpg",
      "assets/project/EXPO HANG MOI DROPPII/tờ roi.jpg",
      "assets/project/EXPO HANG MOI DROPPII/599951886_2944288952438850_7792830380536633948_n.jpg",
      "assets/project/EXPO HANG MOI DROPPII/600274380_3107105886144380_2849238036044173490_n.jpg",
      "assets/project/EXPO HANG MOI DROPPII/598845054_122363898362001820_8402611299852021771_n.jpg",
    ],
  },
  "expo-health": {
    category: "SOCIAL MEDIA | POSM",
    title: "EXPO SỨC KHỎE DROPPII",
    description: "Meta meta meta",
    images: [
      "assets/project/EXPO SUC KHOE DROPPII/thumb expo (1).png",
      "assets/project/EXPO SUC KHOE DROPPII/DIEM HEN SUC KHOE TEASER 2.png",
      "assets/project/EXPO SUC KHOE DROPPII/bia km.png",
      "assets/project/EXPO SUC KHOE DROPPII/TRAI NGHIEM GI.png",
      "assets/project/EXPO SUC KHOE DROPPII/backdrop.png",
      "assets/project/EXPO SUC KHOE DROPPII/standee.png",
      "assets/project/EXPO SUC KHOE DROPPII/pic.png",
    ],
  },
  "sale-event": {
    category: "SOCIAL MEDIA | UI - UX DESIGN",
    title: "SALE EVENT 28.3 DROPPII",
    description: "Meta meta meta",
    images: [
      "assets/project/SALE EVENT DROPPII/thumb 28.png",
      "assets/project/SALE EVENT DROPPII/teaser.png",
      "assets/project/SALE EVENT DROPPII/full rule 28 vuong.png",
      "assets/project/SALE EVENT DROPPII/full rule 28 vuong 2.png",
      "assets/project/SALE EVENT DROPPII/bia km (1).png",
      "assets/project/SALE EVENT DROPPII/LP.png",
    ],
  },
  "sale-campaign-nhan-duyen": {
    category: "SOCIAL MEDIA | POSM",
    title: "EXPO ĐẠI HỘI NĂM DROPPII 2026",
    description: "",
    images: [
    ],
  },
  "vu-lan-nhan-duyen": {
    category: "SOCIAL MEDIA | POSM",
    title: "THÁNG PHỤ NỮ DROPPII",
    description: "Trong khuôn khổ chuỗi hoạt động Tháng Phụ Nữ (10/2025) của Droppii—với các chương trình sale ưu đãi cùng không gian EXPO mua sắm ấm cúng, Tiến đảm nhiệm toàn bộ khâu thiết kế thị giác cho chiến dịch. Từ các bộ Social Media Posts bắt mắt trên Fanpage đến hệ thống POSM in ấn gọn gàng tại khu vực trưng bày như standee, backdrop và tờ rơi, từng thiết kế đều được chăm chút chỉn chu, mang tinh thần tôn vinh phái đẹp và tạo điểm nhấn thu hút khách ghé thăm.",
    images: [
      "assets/project/VU LAN NHAN DUYEN/THUMB phu nu.jpg",
      "assets/project/VU LAN NHAN DUYEN/chuc 2010.png",
      "assets/project/VU LAN NHAN DUYEN/bia.png",
      "assets/project/VU LAN NHAN DUYEN/TEASER.png",
      "assets/project/VU LAN NHAN DUYEN/official.png",
      "assets/project/VU LAN NHAN DUYEN/SALE GIUA THANG.png",
      "assets/project/VU LAN NHAN DUYEN/OFFICIAL-SALE-GIUA-THANG.png",
      "assets/project/VU LAN NHAN DUYEN/VOUCHER-FREESHIP-LIVE.png",
      "assets/project/VU LAN NHAN DUYEN/bia km BIZ.png",
      "assets/project/VU LAN NHAN DUYEN/QUA YEU THUONG DOC.png",
      "assets/project/VU LAN NHAN DUYEN/bia km (1).png",
      "assets/project/VU LAN NHAN DUYEN/bg phu nu.jpg",
      "assets/project/VU LAN NHAN DUYEN/standee phu nu.jpg",
      "assets/project/VU LAN NHAN DUYEN/559502623_122227704656105281_4061632812752644012_n.jpg",
    ],
  },
  "king-jades-83": {
    category: "SOCIAL MEDIA",
    title: "Series APPROVER - 3 màn lọc Droppii",
    description: "",
    images: [
    ],
  },
  "fnb-menu": {
    category: "SOCIAL MEDIA",
    title: "Sale Event 1.6 Droppii",
    description: "",
    images: [
    ],
  },
  "project-moi-1": {
    category: "",
    title: "Gala Đại hội năm Droppii 2024 - 2025",
    description: "",
    images: [
    ],
  },
  "1": {
    category: "SOCIAL MEDIA",
    title: "SERIES KHOẢNH KHẮC VÔ GIÁ DROPPII",
    description: "Series bài viết “Khoảnh Khắc Vô Giá” trên Fanpage Droppii là không gian lắng đọng để ghi dấu và tôn vinh hành trình nỗ lực của các đối tác kinh doanh thông qua những chuyến du lịch tưởng thưởng hàng năm. Đồng hành cùng chiến dịch, Tiến trực tiếp thiết kế toàn bộ các bài đăng Social Media, tập trung vào việc trau chuốt hình ảnh, khéo léo lồng ghép cảm xúc và duy trì tính đồng bộ với nhận diện thương hiệu. Từng thiết kế không chỉ tái hiện trọn vẹn những khoảnh khắc đáng nhớ mà còn tạo cảm hứng truyền động lực mạnh mẽ tới cộng đồng đối tác Droppii.",
    images: [
      "assets/project/1/THUMB kkvg.jpg",
      "assets/project/1/khoanh khac 2.png",
      "assets/project/1/post 1.png",
      "assets/project/1/post 2.png",
      "assets/project/1/post 3png.png",
      "assets/project/1/post 4.png",
    ],
  },
  "yen-sao": {
    category: "Travel",
    title: "KV Droppii Travel",
    description: "",
    images: [
    ],
  },
  "vitaleaf": {
    category: "SOCIAL MEDIA",
    title: "Lá gan nguồn sống - Vitaleaf x Droppii",
    description: "",
    images: [
    ],
  },
  "3": {
    category: "SOCIAL MEDIA",
    title: "Tinh hoa Yến Việt - Droppii x Bestnest",
    description: "",
    images: [
    ],
  },
  "2": {
    category: "",
    title: "Tết đến gần Droppii",
    description: "",
    images: [
    ],
  },
  "ooh": {
    category: "SOCIAL MEDIA | PRINTING",
    title: "Chay Nhân Duyên - Tệp khách Hoa",
    description: "Nhà hàng chay Nhân Duyên là điểm đến ẩm thực thanh tịnh, gói trọn hương vị thực dưỡng lành mạnh và rất được lòng cộng đồng người Hoa tại TP.HCM. Đồng hành cùng định hướng truyền thông của nhà hàng, Tiến trực tiếp đảm nhiệm khâu sáng tạo thị giác—từ việc thiết kế các bộ Social Media Posts bắt mắt, chuẩn phong cách văn hóa trên Fanpage cho đến việc adapt linh hoạt sang hệ thống ấn phẩm in ấn thực tế như băng rôn, standee và poster A5 để bàn. Sự tinh tế trong từng đường nét thiết kế không chỉ tôn vinh nét đẹp ẩm thực chay mà còn tạo sự kết nối gần gũi, thu hút hiệu quả tệp thực khách người Hoa tại địa phương.",
    images: [
      "assets/project/OOH - PANO - BACKDROP/thumb nhan duyen hoa.jpg",
      "assets/project/OOH - PANO - BACKDROP/typo (1).png",
      "assets/project/OOH - PANO - BACKDROP/SOCIAL DAT BAN NHAN MON .png",
      "assets/project/OOH - PANO - BACKDROP/HANH TRINH TAM BAO VUONG.png",
      "assets/project/OOH - PANO - BACKDROP/RULE HANH TRINH TAM BAO.png",
      "assets/project/OOH - PANO - BACKDROP/kim co chi bao.png",
      "assets/project/OOH - PANO - BACKDROP/mon goi 2.png",
      "assets/project/OOH - PANO - BACKDROP/DIMSUM VA TRA.png",
      "assets/project/OOH - PANO - BACKDROP/nam nhay tuong.png",
      "assets/project/OOH - PANO - BACKDROP/post ds.png",
      "assets/project/OOH - PANO - BACKDROP/1 binh tan.png",
      "assets/project/OOH - PANO - BACKDROP/2 (2).png",
      "assets/project/OOH - PANO - BACKDROP/adss.png",
      "assets/project/OOH - PANO - BACKDROP/Set MỘC LIÊN (1).png",
      "assets/project/OOH - PANO - BACKDROP/Set NGỌC HỶ (1).png",
      "assets/project/OOH - PANO - BACKDROP/Set TUỆ TÂM fix (1).png",
      "assets/project/OOH - PANO - BACKDROP/kim ngoc man duong social.png",
      "assets/project/OOH - PANO - BACKDROP/album mon moi.png",
      "assets/project/OOH - PANO - BACKDROP/an chay tich phuoc.png",
      "assets/project/OOH - PANO - BACKDROP/via quan cong.png",
    ],
  },
  "logofolio": {
    category: "SOCIAL MEDIA | PRINTING",
    title: "Chay Nhân Duyên - Tệp khách Việt",
    description: "Nhà hàng chay Nhân Duyên là điểm đến quen thuộc dành cho những ai tìm kiếm không gian ẩm thực thanh tịnh cùng các món chay thực dưỡng, trọn vị và lành lành. Đồng hành cùng hình ảnh của nhà hàng, Tiến đảm nhiệm toàn bộ khâu sáng tạo thị giác—từ việc thiết kế các bộ Social Media Posts chỉn chu, thu hút trên Fanpage đến việc adapt linh hoạt sang hệ thống ấn phẩm in ấn thực tế như băng rôn, standee truyền thông và poster A5 để bàn. Sự đồng bộ từ không gian mạng đến điểm chạm tại nhà hàng đã góp phần mang hình ảnh Nhân Duyên đến gần hơn với thực khách, nhẹ nhàng nhưng đầy ấn tượng.",
    images: [
      "assets/project/LOGOFOLIO/thumb nhan duyen.jpg",
      "assets/project/LOGOFOLIO/gio vang.jpg",
      "assets/project/LOGOFOLIO/dbnm.jpg",
      "assets/project/LOGOFOLIO/social khai truong.png",
      "assets/project/LOGOFOLIO/social retouch.png",
      "assets/project/LOGOFOLIO/social mung 1.png",
      "assets/project/LOGOFOLIO/trang mieng.png",
      "assets/project/LOGOFOLIO/tri an.png",
      "assets/project/LOGOFOLIO/set phung duong.png",
      "assets/project/LOGOFOLIO/MENU TU CHON vuong.png",
      "assets/project/LOGOFOLIO/com chien trai thom.png",
      "assets/project/LOGOFOLIO/pho chay.png",
      "assets/project/LOGOFOLIO/cover.png",
      "assets/project/LOGOFOLIO/cover page vu lan.png",
      "assets/project/LOGOFOLIO/loi nhac.png",
      "assets/project/LOGOFOLIO/com viet.jpg",
      "assets/project/LOGOFOLIO/vu lan.png",
      "assets/project/LOGOFOLIO/1 thang 5 1.png",
      "assets/project/LOGOFOLIO/moc khoa dimsum 2.png",
      "assets/project/LOGOFOLIO/2.9.png",
      "assets/project/LOGOFOLIO/tang 20.10.png",
      "assets/project/LOGOFOLIO/SOCIAL SET SEN.png",
      "assets/project/LOGOFOLIO/SOCIAL VU LAN.png",
      "assets/project/LOGOFOLIO/trung thu poster.png",
      "assets/project/LOGOFOLIO/chuc mung 8.3.png",
      "assets/project/LOGOFOLIO/huong yeu 8.3.png",
      "assets/project/LOGOFOLIO/thich quang duc (1).png",
      "assets/project/LOGOFOLIO/thu ngo.png",
      "assets/project/LOGOFOLIO/tang nen thom social.png",
    ],
  },
  "project-moi-2": {
    category: "SOCIAL MEDIA | POSM",
    title: "KING JADES",
    description: "",
    images: [
    ],
  },
  "project-moi-4": {
    category: "",
    title: "OOH - PANO",
    description: "",
    images: [
    ],
  },
  "project-moi-3": {
    category: "",
    title: "PROJECT MOI 3",
    description: "",
    images: [
    ],
  },
  "bingto-vlog": {
    category: "SOCIAL MEDIA",
    title: "Bingto Vlog - Điền Quân Network",
    description: "Meta meta meta",
    images: [
      "assets/project/ĐIỀN QUÂN NETWORK/cbcbec8a-38d6-4b37-9fd6-b3ad05e4fda9.jpg",
      "assets/project/ĐIỀN QUÂN NETWORK/bingto vlog poster.png",
    ],
  },
  "project-moi-5": {
    category: "",
    title: "NƯỚC ION KỀM FUJIWA",
    description: "",
    images: [
    ],
  },
  "project-moi-6": {
    category: "SOCIAL MEDIA",
    title: "DUNG DỊCH VỆ SINH LADU LENCO",
    description: "",
    images: [
    ],
  },
  "project-moi-7": {
    category: "SOCIAL MEDIA | PRINTING",
    title: "GOODDY BAR - ĐỨC",
    description: "",
    images: [
    ],
  },
  "project-moi-8": {
    category: "EVENT  | PRESENTATION",
    title: "CHƯƠNG TRÌNH ĐÀO TẠO CEO - VCCI",
    description: "Chương trình Đào tạo CEO 2023 do VCCI (Liên đoàn Thương mại và Công nghiệp Việt Nam) tổ chức là khóa huấn luyện cao cấp nhằm nâng tầm năng lực quản trị cho các nhà lãnh đạo doanh nghiệp. Đồng hành cùng sự kiện quy mô này, Tiến trực tiếp thực hiện trọn bộ thiết kế thị giác—từ standee điện tử, backdrop điện tử, ấn phẩm OOH ngoài trời cho đến hệ thống màn hình thuyết trình sân khấu. Sự đồng bộ, sang trọng và chỉn chu trong từng chi tiết thiết kế đã góp phần tôn vinh tính chuyên nghiệp và vị thế cấp cao của chương trình.",
    images: [
      "assets/project/PROJECT MOI 8/thumb vcci (1).jpg",
      "assets/project/PROJECT MOI 8/ooh.jpg",
      "assets/project/PROJECT MOI 8/bg 2.jpg",
      "assets/project/PROJECT MOI 8/bg 1.jpg",
      "assets/project/PROJECT MOI 8/STANDEE VCCI.jpg",
      "assets/project/PROJECT MOI 8/bg mockup.png",
      "assets/project/PROJECT MOI 8/D2200345.JPG",
      "assets/project/PROJECT MOI 8/82f1bb178328701.64e6145af0b3f.jpg",
      "assets/project/PROJECT MOI 8/65edd0178328701.64e6145af1aa2.png",
    ],
  },
  "project-moi-9": {
    category: "Course",
    title: "ART DIRECTION - DẤU ẤN DI SẢN BITIS",
    description: "",
    images: [
    ],
  },
  "project-moi-10": {
    category: "BRANDING",
    title: "LOGOFOLIO - NHIỀU THƯƠNG HIỆU",
    description: "",
    images: [
    ],
  },
};
